spring.application.name=bookReview

# ===============================
# CẤU HÌNH KẾT NỐI POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/book_management_db
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CẤU HÌNH HIBERNATE / JPA
# ===============================
# Tự động tạo/cập nhật bảng dựa trên các class Entity của bạn
spring.jpa.hibernate.ddl-auto=update

# Chọn phương ngữ SQL cho PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hiển thị câu lệnh SQL trên console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true